name: build-with-deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: SSH to server
        run: ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}
      - name: Clone repository
        run: rm -rf /tmp/codeshare && git clone https://github.com/xkamil/codeshare.git /tmp/codeshare
      - name: stop previous app
        run: docker-compose -f /tmp/codeshare/docker-compose.yml down
      - name: deploy
        run: docker-compose -f /tmp/codeshare/docker-compose.yml up -d
      - name: cleanup
        run: rm -rf /tmp/codeshare
