name: build-with-deploy
on:
  push:
    branches:
      - master
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          ssh-private-key: ${{ secrets.PERSONAL_SERVER_SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PERSONAL_SERVER_SSH_HOST }} >> ~/.ssh/known_hosts
      - name: SSH to server
        run: ssh ${{ secrets.PERSONAL_SERVER_USERNAME }}@${{ secrets.PERSONAL_SERVER_SSH_HOST }}
      - name: Run command on server
        run: docker --version